# Generated by Django 4.2.7 on 2023-11-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('MOT', 'Motors'), ('FAS', 'Fashion'), ('ELE', 'Electronics'), ('ART', 'Collectibles & Art'), ('HGA', 'Home & Garden'), ('SPO', 'Sporting Goods'), ('TOY', 'Toys'), ('BUS', 'Business & Industrial'), ('MUS', 'Music')], default='MOT', max_length=3),
        ),
    ]
